import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import galleryMoves from "./lib/gallery-moves.json";

const ADMIN_COOKIE = "artvelle_admin";

// Old gallery URL (pre-2026-08-06 folder layout) → new URL. Generated by
// scripts/tmp/restructure-gallery.mjs when the photo folders were reorganised
// into Category/Subcategory/Product/(common|Variant)/. Keeps every previously
// shared link — order confirmation emails, Google image results, the URLs
// still stored in the database — working forever via a permanent redirect.
const MOVES = galleryMoves as Record<string, string>;

function galleryRedirect(req: NextRequest): NextResponse | null {
  const { pathname } = req.nextUrl;
  if (!pathname.startsWith("/products/gallery/")) return null;
  // The map keys are encodeURI'd (that is how the URLs were stored on
  // products). Normalise whatever encoding the request arrived with.
  let key = pathname;
  try {
    key = encodeURI(decodeURIComponent(pathname));
  } catch {
    // malformed escape sequence — fall through with the raw pathname
  }
  const dest = MOVES[key];
  if (!dest) return null;
  return NextResponse.redirect(new URL(dest, req.url), 308);
}

// Lightweight admin gate: redirect to login if the admin cookie is missing.
// Full JWT verification happens in the admin layout (Node runtime).
export function proxy(req: NextRequest) {
  const moved = galleryRedirect(req);
  if (moved) return moved;

  const { pathname } = req.nextUrl;
  if (pathname.startsWith("/admin") && pathname !== "/admin/login") {
    const hasCookie = req.cookies.has(ADMIN_COOKIE);
    if (!hasCookie) {
      const url = req.nextUrl.clone();
      url.pathname = "/admin/login";
      url.searchParams.set("next", pathname);
      return NextResponse.redirect(url);
    }
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*", "/products/gallery/:path*"],
};
